name: Deploy to Server

on:
  push:
    branches:
      - master # 监听 master 分支的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server
      env:
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        # 配置 SSH 密钥
        mkdir -p ~/.ssh
        echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # 连接到远程服务器
        ssh-keyscan -H ${{ secrets.TENCENT_SH_HOST }} >> ~/.ssh/known_hosts
        scp -r ./ ${{ secrets.TENCENT_SH_USERNAME }}@${{ secrets.TENCENT_SH_HOST }}:${{ secrets.DEPLOY_PATH }}
